### PR TITLE
#4 Add possibility to filter pages by the URL parameter

### PR DESCRIPTION
**Pull request by zeleznypa**
Possible solution for the #4

### CODE REVIEW

**Comment by PontusHorn** [comment]
Seems like a reasonable feature to have! I have just a minor issue with the implementation: by merging the two sets of tags (from the page and from the parameter) it matches pages having any tag from either set, whereas I think it would make more sense to make it match pages that both sets.

For example: Say we have a /blog page with `Filter: blog` in the meta header. Then you'd expect /blog?filter=food to show you blog posts about food, right? In other words, posts with _both_ the "blog" and "food" tags, rather than either.

Would you mind changing it to that behaviour, or do you have a good case for the current behaviour?

**Comment by zeleznypa** [comment]
At this time I tried to have a blog :) All pages are "blog" and i want to filter them by tags. It will be usefull to filter them both way like you wrote, but when all pages are "blog", why I have to filter them for "blog" label? ;)

**Comment by PontusHorn** [comment]
That's fair for your use case, but I think to be as useful as possible for other people, it's best to change it to require both when both are supplied. If you don't feel like making the change, I can probably take care of it at some point.

**Comment by PontusHorn** [comment]
Gonna close this as I apparently am never going to get around to doing this myself 😄 If anyone else is up for making this change, feel free.

**Pull request closed without merging**
